name: test ump_24.c
run-name: test1 triggered bt ${{ github.actor }}
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
on:
  label:
    types:
      - created
      - edited
      - deleted
  push:
    branches:
      - main
      - "**"
  schedule:
    - cron: "12 3 * * *"
jobs:
  test-ubuntu:
    name: test in ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Compile code
        run: gcc -Wall -Wextra program/ump_24.c -o ump_24_ubuntu
      - name: Run tests
        run: |
          for ((i=1; i<=20; i++)); do
            input="test/test_ump_24/${i}.in"
            expected="test/test_ump_24/${i}.out"
            if ./ump_24_ubuntu < "$input" | cmp -s - "$expected"; then
              echo "test ${i} accepted"
            else
              echo "test ${i} unaccepted"
              exit 1
            fi
          done
  test-macos:
    name: test in macOS
    runs-on: macos-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Compile code
          run: gcc -Wall -Wextra program/ump_24.c -o ump_24_macos
        - name: Run tests
          run: |
            for ((i=1; i<=20; i++)); do
              input="test/test_ump_24/${i}.in"
              expected="test/test_ump_24/${i}.out"
              if ./ump_24_macos < "$input" | cmp -s - "$expected"; then
                echo "test ${i} accepted"
              else
                echo "test ${i} unaccepted"
                echo "$(./ump_24_macos < "$input")"
                exit 1
              fi
            done
  test-windows:
    name: test in windows
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Compile code
        run: gcc -Wall -Wextra program/ump_24.c -o ump_24_windows
      - name: Run tests
        run: |
          bash -c 'for ((i=1; i<=20; i++)); do
            input="test/test_ump_24/${i}.in"
            expected="test/test_ump_24/${i}.out"
            if ./ump_24_windows < "$input" | cmp -s - "$expected"; then
                echo "test ${i} accepted"
            else
                echo "test ${i} unaccepted"
                echo "$(./ump_24_windows < "$input")"
                exit 1
            fi
            done'
